server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name ${CUT_DANA_PLATFORM_HOST} nginx;

  location = /health {
      allow 127.0.0.1;
      allow ::1;
      allow 172.16.0.0/12;
      deny all;

      access_log off;
      add_header Content-Type text/plain;
      return 200 "healthy\n";
  }

  # Alles andere zu HTTPS umleiten
  location / {
      return 308 https://$http_host$request_uri;
  }
}


server {

  client_max_body_size 0;
  client_header_buffer_size 1024k;
  large_client_header_buffers 4 64k;
  proxy_buffer_size          128k;
  proxy_buffers            4 256k;
  proxy_busy_buffers_size    256k;

  include /etc/nginx/gzip.conf;

  include /etc/nginx/ssl.conf;
  ssl_certificate /etc/ssl/certs/fullchain.pem;
  ssl_certificate_key /etc/ssl/private/cert.key;

  server_name ${CUT_DANA_PLATFORM_HOST} nginx;

  # Docker's internal DNS server, cached for 30 seconds.
  resolver 127.0.0.11 valid=30s;

  location = /health {
    # TODO: replace with real content asap
    access_log off;
    add_header Content-Type text/plain;
    return 200 "healthy\n";
  }

  location / {
    set $upstream_masterportal masterportal;
    proxy_pass http://$upstream_masterportal;
    include /etc/nginx/proxy_params;
  }

  location ^~ /mastercode/ {
    set $upstream_masterportal masterportal;
    rewrite ^/mastercode/(.*)$ /portal/mastercode/$1 break;
    proxy_pass http://$upstream_masterportal;
    include /etc/nginx/proxy_params;
  }

  location /auth/ {
    set $upstream_keycloak keycloak-app:8080;
    proxy_pass http://$upstream_keycloak;
    include /etc/nginx/proxy_params;
  }

  location /api/ {
    set $upstream_backend backend:8000;
    rewrite ^/api/(.*) /$1 break;
    proxy_pass http://$upstream_backend;
    include /etc/nginx/proxy_params;
  }

}

server {
  client_max_body_size 0;
  client_header_buffer_size 1024k;
  large_client_header_buffers 4 64k;
  proxy_buffer_size          128k;
  proxy_buffers            4 256k;
  proxy_busy_buffers_size    256k;

  include /etc/nginx/gzip.conf;
  include /etc/nginx/ssl.conf;
  ssl_certificate /etc/ssl/certs/fullchain.pem;
  ssl_certificate_key /etc/ssl/private/cert.key;

  server_name ${CUT_DANA_S3_HOST} nginx;

  # Docker's internal DNS server, cached for 30 seconds.
  resolver 127.0.0.11 valid=30s;

  location / {
    set $upstream_minio garage:3900;
    proxy_pass http://$upstream_minio;
    include /etc/nginx/proxy_params;
  }

}
